FROM ubuntu:noble
LABEL maintainer="kontakt@nethotline.io"

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
ENV DEBIAN_FRONTEND=noninteractive

COPY --chmod=700 build/ /tmp/build/
RUN /tmp/build/install_base.sh
